export const PROFILES = [
    {
        id:0,
        link:'https://www.codechef.com/users/akhilkumar31e',
        name:'Codechef'
    },
    {
        id:1,
        link:'https://www.hackerrank.com/akhilkumar31e',
        name:'Hackerrank'
    },
    {
        id:2,
        link:'https://leetcode.com/akhilkumar31e/',
        name:'LeetCode'
    },
    {
        id:4,
        link:'https://www.interviewbit.com/profile/akhilkumar31e6712',
        name:'InterviewBit'
    },
    {
        id:3,
        link:'https://www.spoj.com/users/akhilkumar31e/',
        name:'SPOJ'
    }
]